Adding some static blocks and gamepedia links.
bleroy/minecraft.client pull request #15
Opened 2016-11-22 20:46 UTC by Flosus

This PR adds the following new blocks:

- Bone
- Jukebox
- IronBars
- SoulSand
- Netherrack
- Hay
- JackOLantern 
- Leaves
- Magma
- Melon
- Pumpkin
- QuartzOre
- Quartz
- TNT
- WaterLily

In addition it adds summaries to all block (common) block types. I wasn't sure how to handle the different door types, so I'm open for suggestions (looking forwards to trapdoors and other multiblocks)

An unnecessary check got removed and the .idea-folder from the IDE Raider got it's place in the .ignore file.

2016-11-22 21:04 UTC, Flosus commented
There are still some comments wrong... Will fix now

2016-11-22 21:04 UTC, Flosus commented on Decent.Minecraft.Client/Blocks/Coal.cs
>      public class Charcoal : Coal
Just noticed this one... There is no Charcoal block in the game, but the Coal ore block is missing.

2016-11-23 00:03 UTC, bleroy commented
This looks great. Thanks for the contribution. I'll merge as soon as you make the couple of changes that I put in comments. Or I can merge and fix myself, whichever you prefer.

2016-11-23 00:03 UTC, bleroy requested changes

2016-11-23 00:03 UTC, bleroy commented on Decent.Minecraft.Client/Blocks/Bed.cs
> +    /// Beds are made out of a <see cref="BedFoot">foot</see> and a <see cref="BedFoot">head</see> part.<br />
The "see" tag for head is wrong.

2016-11-23 00:03 UTC, bleroy commented on Decent.Minecraft.Client/Blocks/Coal.cs
>      public class Charcoal : Coal
Right: this is an abstraction of a block of coal that has the charred bit set.

2016-11-23 00:03 UTC, bleroy commented on Decent.Minecraft.Client/Blocks/Fire.cs
> +            if (intensity > 15)
No, the right fix is to make the intensity an `int`, like I have on other blocks that take a numeric parameter. I made that change so we don't have that many casts around the code. The benefit of using a byte is negligible, but the drawbacks are everywhere.

2016-11-23 05:24 UTC, Flosus commented
I will fix it.

2016-11-23 09:29 UTC, Flosus commented on Decent.Minecraft.Client/Blocks/Coal.cs
>      public class Charcoal : Coal
So, what is the solution here? should I remove the IsCharred property and make the Charcoal : Coal class to a CoalOre : Block class?

2016-11-23 17:36 UTC, bleroy commented on Decent.Minecraft.Client/Blocks/Coal.cs
>      public class Charcoal : Coal
Leave `Coal` and `Charcoal` as they currently are, except make the gamepedia link point to `Block_of_Coal` for both of those. Then add `CoalOre:Block`, separately.

2016-11-23 17:38 UTC, bleroy approved these changes

2016-11-23 18:23 UTC, Flosus commented on Decent.Minecraft.Client/Blocks/Coal.cs
>      public class Charcoal : Coal
Ok, will do it, but I still don't get it :( There is no charcoal block in the game and the wiki says:

> Blocks of coal can only be crafted with regular coal, not charcoal.

2016-11-23 19:12 UTC, bleroy commented on Decent.Minecraft.Client/Blocks/Coal.cs
>      public class Charcoal : Coal
No, you're right. I'm the one who got confused: the coal *object* has a charred state, but not the block. You are right, the charred data and the corresponding serialization code should be removed. Sorry about the misunderstanding.

2016-11-23 19:23 UTC, Flosus commented on Decent.Minecraft.Client/Blocks/Coal.cs
>      public class Charcoal : Coal
Should I patch it or do you want to do it?

2016-11-23 19:31 UTC, bleroy commented on Decent.Minecraft.Client/Blocks/Coal.cs
>      public class Charcoal : Coal
Either way is fine by me.

2016-11-23 20:38 UTC, Flosus commented on Decent.Minecraft.Client/Blocks/Coal.cs
>      public class Charcoal : Coal
I removed it with the last commit

2016-11-23 21:30 UTC, merged

2016-11-23 21:30 UTC, bleroy commented
Thanks!